version: "3.9"

services:
  loadbalancer:
    build: ./loadbalancer
    container_name: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - loadbalancer

networks:
  net1:
    name: net1
    external: false

